data<-read.csv("E:/XSTK/CSV/data.csv")
View(data)
head(data,10)
apply(is.na(data),2,which)
data$infill_pattern=as.factor(data$infill_pattern)
summary(data$infill_pattern)
data$material=as.factor(data$material)
summary(data$material)
apply(is.na(data),2,which)
summary(data)
boxplot(data$roughness~data$infill_pattern)
boxplot(data$roughness~data$material)
hist(data$roughness,main="Histogram of roughness",xlab="roughness",col=heat.colors(5))
hist(data$tension_strenght,main="Histogram of tension_strenght",xlab="tension_strenght",col=heat.colors(5))
hist(data$elongation,main="Histogram of elongation",xlab="elongation",col=heat.colors(5))
boxplot(data$tension_strenght~data$infill_pattern)
boxplot(data$tension_strenght~data$material)
boxplot(data$elongation~data$infill_pattern)
boxplot(data$elongation~data$material)
model_1<-lm(roughness~layer_height+wall_thickness+infill_density+nozzle_temperature+bed_temperature+infill_pattern+print_speed+material,data)
summary(model_1)
model_2<-lm(roughness~layer_height+nozzle_temperature+bed_temperature+print_speed+material,data)
summary(model_2)
anova(model_1,model_2)
par(mfrow=c(2,2))
plot(model_2)
re<-residuals(model_2)
shapiro.test(re)
re<-residuals(model_2)
t.test(re,mu=0)
model_3<-lm(tension_strenght~layer_height+wall_thickness+infill_density+nozzle_temperature+bed_temperature+infill_pattern+print_speed+material,data)
summary(model_3)
model_4<-lm(tension_strenght~layer_height+wall_thickness+infill_density+nozzle_temperature+bed_temperature+material,data)
summary(model_4)
anova(model_3,model_4)
par(mfrow=c(2,2))
plot(model_4)
re<-residuals(model_4)
shapiro.test(re)
re<-residuals(model_4)
t.test(re,mu=0)
model_5<-lm(elongation~layer_height+wall_thickness+infill_density+nozzle_temperature+bed_temperature+infill_pattern+print_speed+material,data)
summary(model_5)
model_6<-lm(elongation~layer_height+infill_density+nozzle_temperature+bed_temperature+material,data)
summary(model_6)
anova(model_5,model_6)
plot(model_6)
re<-residuals(model_6)
shapiro.test(re)
re<-residuals(model_6)
t.test(re,mu=0)

# đồ thị tương quan.
data<-read.csv("E:/XSTK/CSV/data.csv")
data$infill_pattern = as.factor(data$infill_pattern)
data$material = as.factor(data$material)
data$infill_pattern = as.numeric(data$infill_pattern)
data$material = as.numeric(data$material)
View(data)
summary(data)
cor(data)
c <-cor(data)
library(corrplot)
corrplot(c)
corrplot(c, order = "AOE" ,method = "color", addCoef.col = "Gray")





