setwd("C:/")
df <- read.csv("BTLXSTK.csv")
df
new_df <- df[,c("is_expedited_delivery","order_price","delivery_charges", "coupon_discount","order_total","distance_to_nearest_warehouse","is_happy_customer")]
apply(is.na(new_df),2,which) 
new_df2 <- new_df
new_df2[,c("is_expedited_delivery","order_price","delivery_charges", "coupon_discount","order_total","distance_to_nearest_warehouse")]<-log(new_df2[,c("is_expedited_delivery","order_price","delivery_charges", "coupon_discount","order_total","distance_to_nearest_warehouse")]+1)
mean<-apply(new_df,2,mean) 
sd<-apply(new_df,2,sd) 
median<-apply(new_df,2,median) 
Q1<-apply(new_df,2,quantile,probs=0.25) 
Q3<-apply(new_df,2,quantile,probs=0.75) 
max<-apply(new_df,2,max) 
min<-apply(new_df,2,min) 
otput<-cbind(mean,median,sd,min,max,Q1,Q3) 
mean<-apply(new_df2,2,mean) 
sd<-apply(new_df2,2,sd) 
median<-apply(new_df2,2,median) 
Q1<-apply(new_df2,2,quantile,probs=0.25) 
Q3<-apply(new_df2,2,quantile,probs=0.75) 
max<-apply(new_df2,2,max) 
min<-apply(new_df2,2,min) 
otput<-cbind(mean,median,sd,min,max,Q1,Q3) 
hist(new_df[,"is_expedited_delivery"],xlab="is_expedited_delivery ",main="Histogram of 
 is_expedited_delivery",ylim=c(0,500),col=2,labels=T)
hist(new_df2[,"is_expedited_delivery"] ,xlab="log(is_expedited_delivery +1) ",main="Histogram of log( is_expedited_delivery+1)",ylim=c(0,500),col=3,labels=T)
hist(new_df[,"order_price"],xlab="order_price ",main="Histogram of 
 order_price",ylim=c(0,500),col=2,labels=T)
hist(new_df2[,"order_price"],xlab="log(order_price+1) ",main="Histogram of 
 log(order_price+1)",ylim=c(0,500),col=3,labels=T)
hist(new_df[,"delivery_charges"],xlab="delivery_charges ",main="Histogram of 
 delivery_charges",ylim=c(0,500),col=2,labels=T)
hist(new_df2[,"delivery_charges"],xlab="log(delivery_charges+1) ",main="Histogram of 
 log(delivery_charges+1)",ylim=c(0,500),col=3,labels=T)
hist(new_df[,"coupon_discount"],xlab=" coupon_discount ",main="Histogram of 
coupon_discount",ylim=c(0,500),col=2,labels=T)
hist(new_df2[,"coupon_discount"],xlab="log(coupon_discount+1) ",main="Histogram of 
 log(coupon_discount+1)",ylim=c(0,500),col=3,labels=T)
hist(new_df[,"order_total"],xlab=" order_total",main="Histogram of 
order_total",ylim=c(0,500),col=2,labels=T)
hist(new_df2[,"order_total"],xlab="log(order_total+1) ",main="Histogram of 
 log(order_total+1)",ylim=c(0,500),col=3,labels=T)
hist(new_df[,"distance_to_nearest_warehouse"],xlab=" distance_to_nearest_warehouse",main="Histogram of distance_to_nearest_warehouse",ylim=c(0,500),col=2,labels=T)
hist(new_df2[,"distance_to_nearest_warehouse"],xlab="log(distance_to_nearest_warehouse+1) ",main="Histogram of log(distance_to_nearest_warehouse+1)",ylim=c(0,500),col=3,labels=T)
hist(new_df[,"is_happy_customer"],xlab=" is_happy_customer",main="Histogram of is_happy_customer ",ylim=c(0,500),col=2,labels=T)
hist(new_df2[,"is_happy_customer"],xlab="log(is_happy_customer+1) ",main="Histogram of log(is_happy_customer+1)",ylim=c(0,500),col=3,labels=T)
plot(is_happy_customer~ is_expedited_delivery,data=new_df,xlab=" is_expedited_delivery ",ylab="is_happy_customer",main="Plot of is_happy_customer and is_expedited_delivery ",col=2)
plot(is_happy_customer~ is_expedited_delivery,data=new_df2,xlab=" log(is_expedited_delivery +1)",ylab="is_happy_customer",main="Plot of is_happy_customer and log(is_expedited_delivery+1) ",col=3)
plot(is_happy_customer~ order_price,data=new_df,xlab=" order_price",ylab="is_happy_customer",main="Plot of is_happy_customer and order_price",col=2)
plot(is_happy_customer~ order_price,data=new_df2,xlab=" log(order_price+1)",ylab="is_happy_customer",main="Plot of is_happy_customer and log(order_price+1) ",col=3)
plot(is_happy_customer~ delivery_charges,data=new_df,xlab=" delivery_charges",ylab="is_happy_customer",main="Plot of is_happy_customer and delivery_charges",col=2)
plot(is_happy_customer~ delivery_charges,data=new_df2,xlab=" log(delivery_charges+1)",ylab="is_happy_customer",main="Plot of is_happy_customer and log(delivery_charges+1) ",col=3)
plot(is_happy_customer~ coupon_discount,data=new_df,xlab=" coupon_discount",ylab="is_happy_customer",main="Plot of is_happy_customer and coupon_discount",col=2)
plot(is_happy_customer~ coupon_discount,data=new_df2,xlab=" log(coupon_discount+1)",ylab="is_happy_customer",main="Plot of is_happy_customer and log(coupon_discount+1) ",col=3)
plot(is_happy_customer~ order_total,data=new_df,xlab=" order_total",ylab="is_happy_customer",main="Plot of is_happy_customer and order_total",col=2)
plot(is_happy_customer~ order_total,data=new_df2,xlab=" log(order_total+1)",ylab="is_happy_customer",main="Plot of is_happy_customer and log(order_total+1) ",col=3)
plot(is_happy_customer~ is_expedited_delivery,data=new_df,xlab=" is_expedited_delivery",ylab="is_happy_customer",main="Plot of is_happy_customer and is_expedited_delivery",col=2)
plot(is_happy_customer~ is_expedited_delivery,data=new_df2,xlab=" log(is_expedited_delivery+1)",ylab="is_happy_customer",main="Plot of is_happy_customer and log(is_expedited_delivery+1) ",col=3)
install.packages('caTools')
library(caTools)
set.seed(100)
split= sample.split(new_df2$is_happy_customer,SplitRatio = 0.65)
mauxaydung = subset(new_df2,split==TRUE)
maukiemdinh = subset(new_df2,split==FALSE)
mohinh = glm(is_happy_customer~.,data=mauxaydung,family = binomial)
summary(mohinh)
dubaoxaydung = predict(mohinh,type="response",newdata= mauxaydung)
summary(dubaoxaydung)
dubaokiemdinh = predict(mohinh,type="response",newdata= maukiemdinh)
summary(dubaokiemdinh)
table(maukiemdinh$is_happy_customer,dubaokiemdinh>0.5)
(21+115)/nrow(maukiemdinh)
mohinh2 = glm(is_happy_customer~ is_expedited_delivery+ delivery_charges,data=mauxaydung,family = binomial)
summary(mohinh2)
dubaokiemdinh = predict(mohinh2,type="response",newdata= maukiemdinh)
summary(dubaokiemdinh)
table(maukiemdinh$is_happy_customer,dubaokiemdinh>0.5)
(21+117)/nrow(maukiemdinh)
anova(mohinh, mohinh2, test = "Chisq")
plot(mohinh2)

